import type { SectionDef } from "./types";

export const POLICY_VERSION = "1.0";

export const sections: SectionDef[] = [
  {
    id: "negocio",
    title: "Información del negocio",
    intro:
      "Empecemos por lo básico. Solo el nombre y una breve descripción son obligatorios.",
    fields: [
      {
        id: "businessName",
        type: "text",
        label: "Nombre del negocio",
        placeholder: "Ej: Restaurante Sa Caleta",
        help: "Tal y como quieres que aparezca en la web.",
      },
      {
        id: "description",
        type: "textarea",
        label: "Descripción breve",
        placeholder: "En una o dos frases, ¿a qué os dedicáis?",
      },
      {
        id: "areas",
        type: "text",
        label: "Localidad o zonas donde trabajáis",
        placeholder: "Ej: Menorca · Maó · Ciutadella",
        optional: true,
      },
      {
        id: "foundedYear",
        type: "text",
        label: "Año de creación",
        placeholder: "Ej: 2015",
        optional: true,
      },
      {
        id: "showAddress",
        type: "reveal",
        label: "¿Quieres que aparezca vuestra dirección física en la web?",
        fields: [
          {
            id: "address",
            type: "text",
            label: "Dirección",
            placeholder: "Ej: C/ Major 12, Maó",
            optional: true,
          },
        ],
      },
      {
        id: "showHours",
        type: "reveal",
        label: "¿Quieres que aparezca el horario de atención?",
        fields: [
          {
            id: "hours",
            type: "textarea",
            label: "Horario",
            placeholder: "Ej: L-V 9:00-18:00 · S 10:00-14:00",
            optional: true,
          },
        ],
      },
      {
        id: "currentWebsite",
        type: "url",
        label: "Enlace a tu web actual",
        placeholder: "https://...",
        help: "Si ya tienes una, aunque sea antigua.",
        optional: true,
      },
      {
        id: "googleMaps",
        type: "url",
        label: "Enlace a tu ficha de Google Maps",
        placeholder: "https://maps.app.goo.gl/...",
        optional: true,
      },
    ],
  },
  {
    id: "contacto",
    title: "Datos de contacto",
    intro: "Cómo queréis que os contacten desde la web.",
    fields: [
      {
        id: "phone",
        type: "tel",
        label: "Teléfono",
        placeholder: "Ej: 640 662 892",
      },
      {
        id: "differentWhatsapp",
        type: "reveal",
        label: "¿Tu WhatsApp es distinto del teléfono?",
        fields: [
          {
            id: "whatsapp",
            type: "tel",
            label: "Número de WhatsApp",
            placeholder: "Ej: 640 662 892",
            optional: true,
          },
        ],
      },
      {
        id: "publicEmail",
        type: "email",
        label: "Correo electrónico público",
        placeholder: "hola@tunegocio.com",
        help: "El que se mostrará en la web.",
        optional: true,
      },
      {
        id: "formsEmail",
        type: "email",
        label: "Correo para recibir los formularios",
        placeholder: "tucorreo@tunegocio.com",
        help: "Donde llegarán los mensajes que os envíen desde la web.",
        optional: true,
      },
      {
        id: "socials",
        type: "textarea",
        label: "Enlaces a redes sociales",
        placeholder: "Instagram, Facebook, TikTok... un enlace por línea",
        optional: true,
      },
    ],
  },
  {
    id: "identidad",
    title: "Identidad visual",
    intro:
      "Si tienes estos archivos a mano, súbelos. Si no, salta tranquilamente esta sección.",
    optionalSection: true,
    fields: [
      {
        id: "logo",
        type: "files",
        label: "Logo",
        help: "PNG, SVG, JPG... puedes subir varias versiones.",
        accept: "image/*,.svg,.ai,.eps,.pdf",
        optional: true,
      },
      {
        id: "brandColors",
        type: "text",
        label: "Colores de marca",
        placeholder: "Ej: morado #7C3AED, negro, blanco",
        optional: true,
      },
      {
        id: "brandFonts",
        type: "text",
        label: "Tipografías de marca",
        placeholder: "Ej: Montserrat, Georgia...",
        optional: true,
      },
      {
        id: "brandManual",
        type: "files",
        label: "Manual de identidad visual",
        accept: ".pdf,image/*",
        optional: true,
      },
      {
        id: "brandGraphics",
        type: "files",
        label: "Otros elementos gráficos",
        help: "Iconos, patrones, ilustraciones de marca...",
        accept: "image/*,.svg,.pdf,.zip",
        optional: true,
      },
      {
        id: "avoidColors",
        type: "text",
        label: "Colores o estilos que NO quieres",
        placeholder: "Ej: nada de rojo, evitar diseños recargados",
        optional: true,
      },
    ],
  },
  {
    id: "servicios",
    title: "Servicios o productos",
    intro: "Añade lo que ofreces. Puedes incluir tantos como quieras.",
    fields: [
      {
        id: "services",
        type: "repeatable",
        label: "Tus servicios o productos",
        itemLabel: "Servicio / producto",
        addLabel: "Añadir otro servicio o producto",
        startWith: 1,
        fields: [
          { id: "name", type: "text", label: "Nombre", placeholder: "Ej: Reformas integrales" },
          {
            id: "description",
            type: "textarea",
            label: "Descripción",
            placeholder: "¿En qué consiste? ¿Qué incluye?",
            optional: true,
          },
          {
            id: "price",
            type: "text",
            label: "Precio (si debe aparecer)",
            placeholder: "Ej: desde 90€",
            optional: true,
          },
        ],
      },
      {
        id: "mainService",
        type: "text",
        label: "¿Cuál es tu servicio o producto principal?",
        placeholder: "El que más vendes o quieres destacar",
        optional: true,
      },
    ],
  },
  {
    id: "sobre-negocio",
    title: "Sobre tu negocio",
    intro:
      "Esto nos ayuda a contar tu historia. Responde lo que puedas, todo es opcional.",
    optionalSection: true,
    fields: [
      {
        id: "history",
        type: "textarea",
        label: "Historia y origen del negocio",
        placeholder: "¿Cómo y por qué nació?",
        optional: true,
      },
      {
        id: "problemSolved",
        type: "textarea",
        label: "¿Qué problema resuelves a tus clientes?",
        placeholder: "La necesidad principal que cubres.",
        optional: true,
      },
      {
        id: "differentiator",
        type: "textarea",
        label: "¿Qué te diferencia de la competencia?",
        placeholder: "Eso que haces distinto o mejor.",
        optional: true,
      },
      {
        id: "mostValued",
        type: "textarea",
        label: "¿Qué es lo que más valoran tus clientes?",
        optional: true,
      },
      {
        id: "importantInfo",
        type: "textarea",
        label: "Algo importante que debamos saber",
        placeholder: "Cualquier detalle clave para tu web.",
        optional: true,
      },
    ],
  },
  {
    id: "publico",
    title: "Público objetivo",
    intro: "A quién quieres llegar con tu web.",
    optionalSection: true,
    fields: [
      {
        id: "idealClient",
        type: "textarea",
        label: "Describe a tu cliente ideal",
        placeholder: "Edad, perfil, qué busca...",
        optional: true,
      },
      {
        id: "audienceType",
        type: "options",
        label: "¿A quién te diriges?",
        options: ["Particulares", "Empresas", "Ambos"],
        optional: true,
      },
      {
        id: "clientToAttract",
        type: "textarea",
        label: "¿Qué tipo de cliente quieres atraer?",
        placeholder: "Si es distinto del que tienes ahora.",
        optional: true,
      },
    ],
  },
  {
    id: "textos",
    title: "Textos y mensajes",
    intro:
      "Si ya tienes textos, súbelos. Si no, nosotros los redactamos por ti.",
    optionalSection: true,
    fields: [
      {
        id: "textFiles",
        type: "files",
        label: "Documentos con textos o información",
        help: "Word, PDF, notas... lo que tengas.",
        accept: ".pdf,.doc,.docx,.txt,.rtf,.odt,.pages",
        optional: true,
      },
      {
        id: "slogan",
        type: "text",
        label: "Eslogan o frase principal",
        placeholder: "Si tienes una.",
        optional: true,
      },
      {
        id: "mustPhrases",
        type: "textarea",
        label: "Mensajes que deben aparecer sí o sí",
        optional: true,
      },
      {
        id: "tone",
        type: "options",
        label: "Tono de comunicación",
        options: [
          "Cercano y familiar",
          "Profesional y serio",
          "Moderno y desenfadado",
          "Elegante y premium",
          "No estoy seguro",
        ],
        optional: true,
      },
      {
        id: "avoidInfo",
        type: "textarea",
        label: "Información o palabras que NO deben aparecer",
        optional: true,
      },
    ],
  },
  {
    id: "equipo",
    title: "Equipo",
    intro:
      "Opcional. Solo si quieres mostrar a las personas que hay detrás del negocio.",
    optionalSection: true,
    fields: [
      {
        id: "team",
        type: "repeatable",
        label: "Miembros del equipo",
        itemLabel: "Persona",
        addLabel: "Añadir persona",
        startWith: 0,
        optional: true,
        fields: [
          { id: "name", type: "text", label: "Nombre", placeholder: "Ej: Marta García" },
          { id: "role", type: "text", label: "Cargo", placeholder: "Ej: Fundadora", optional: true },
          {
            id: "bio",
            type: "text",
            label: "Breve descripción",
            placeholder: "Una línea sobre esta persona.",
            optional: true,
          },
        ],
      },
      {
        id: "teamPhotos",
        type: "files",
        label: "Fotos del equipo",
        accept: "image/*",
        optional: true,
      },
    ],
  },
  {
    id: "fotos",
    title: "Fotografías y vídeos",
    intro:
      "Sube el material que tengas. La calidad de las fotos marca mucho el resultado, pero todo es opcional.",
    optionalSection: true,
    fields: [
      {
        id: "photosBusiness",
        type: "files",
        label: "Fotos del negocio o instalaciones",
        accept: "image/*",
        optional: true,
      },
      {
        id: "photosProducts",
        type: "files",
        label: "Fotos de productos o servicios",
        accept: "image/*",
        optional: true,
      },
      {
        id: "photosWork",
        type: "files",
        label: "Fotos de trabajos o proyectos realizados",
        accept: "image/*",
        optional: true,
      },
      {
        id: "videos",
        type: "files",
        label: "Vídeos",
        help: "Si son muy pesados, sube el enlace en el campo de abajo.",
        accept: "video/*",
        optional: true,
      },
      {
        id: "videoLinks",
        type: "textarea",
        label: "Enlaces a vídeos",
        placeholder: "YouTube, Vimeo, Drive... un enlace por línea",
        optional: true,
      },
      {
        id: "photosPermission",
        type: "checkbox",
        label: "Confirmo que tengo permiso para usar los archivos que he subido.",
        optional: true,
      },
    ],
  },
  {
    id: "confianza",
    title: "Reseñas y confianza",
    intro:
      "Elementos que generan confianza en tus clientes. Todo opcional.",
    optionalSection: true,
    fields: [
      {
        id: "reviews",
        type: "repeatable",
        label: "Reseñas o testimonios",
        itemLabel: "Reseña",
        addLabel: "Añadir reseña",
        startWith: 0,
        optional: true,
        fields: [
          {
            id: "text",
            type: "textarea",
            label: "Reseña o testimonio",
            placeholder: "Lo que dijo el cliente.",
          },
          { id: "author", type: "text", label: "Nombre", placeholder: "Quién la dejó", optional: true },
        ],
      },
      {
        id: "clientLogos",
        type: "files",
        label: "Logos de clientes o colaboradores",
        accept: "image/*,.svg,.pdf",
        optional: true,
      },
      {
        id: "certifications",
        type: "text",
        label: "Certificaciones, premios o asociaciones",
        placeholder: "Ej: ISO 9001, premio X, miembro de...",
        optional: true,
      },
      {
        id: "experienceData",
        type: "text",
        label: "Años de experiencia o nº de clientes",
        placeholder: "Ej: +10 años · +500 clientes",
        optional: true,
      },
    ],
  },
  {
    id: "referencias",
    title: "Referencias visuales",
    intro: "Para entender el estilo que tienes en mente.",
    optionalSection: true,
    fields: [
      {
        id: "likedSites",
        type: "textarea",
        label: "Webs que te gustan y por qué",
        placeholder: "Pega los enlaces y di qué te gusta de cada uno.",
        optional: true,
      },
      {
        id: "dislikedSites",
        type: "textarea",
        label: "Webs que NO te gustan y por qué",
        optional: true,
      },
      {
        id: "threeWords",
        type: "text",
        label: "Tres palabras que definan tu marca",
        placeholder: "Ej: confianza, cercanía, modernidad",
        optional: true,
      },
      {
        id: "designPreference",
        type: "options",
        label: "¿Qué tipo de diseño prefieres?",
        options: [
          "Más visual (imágenes e impacto)",
          "Más informativo (textos y detalle)",
          "Equilibrado",
        ],
        optional: true,
      },
    ],
  },
  {
    id: "legal",
    title: "Información legal",
    intro:
      "Necesaria para los textos legales de la web (aviso legal, privacidad...).",
    optionalSection: true,
    fields: [
      {
        id: "legalName",
        type: "text",
        label: "Nombre o razón social",
        placeholder: "Ej: Nombre Apellidos / Empresa S.L.",
        optional: true,
      },
      {
        id: "nif",
        type: "text",
        label: "NIF o CIF",
        optional: true,
      },
      {
        id: "fiscalAddress",
        type: "textarea",
        label: "Domicilio fiscal",
        optional: true,
      },
      {
        id: "legalEmail",
        type: "email",
        label: "Correo electrónico legal",
        placeholder: "Para notificaciones legales.",
        optional: true,
      },
      {
        id: "legalDocs",
        type: "files",
        label: "Textos legales que ya tengas",
        help: "Aviso legal, política de privacidad, cookies, condiciones...",
        accept: ".pdf,.doc,.docx,.txt",
        optional: true,
      },
    ],
  },
];
